# Generated by Django 4.2.5 on 2023-10-05 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch_if', '0002_subcategory_tv_shows_season_movies_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='content_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tv_shows',
            name='content_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='content/images/')),
                ('video_url', models.URLField(blank=True, max_length=255)),
                ('content_creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_if.subcategory')),
            ],
        ),
    ]
