# Generated by Django 4.2.5 on 2023-10-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_if', '0003_movies_content_creator_tv_shows_content_creator_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='kids',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
