# Generated by Django 4.2.5 on 2023-10-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_if', '0007_subscriber_remove_kids_rating_remove_movies_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
