# Generated by Django 4.2.5 on 2023-10-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_if', '0008_alter_episode_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tv_show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watch_if.tv_shows'),
        ),
    ]
